image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - ./install.sh
  - source venv/bin/activate

test:
  script:
    - make test

deploy-dev:
  script:
    - make deploy-dev
  only:
    - develop

deploy-prod:
  script:
    - make deploy-prod
  only:
    - master
