image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - secrets
  - test
  - deploy-dev
  - deploy-prod

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - ./install.sh
  - source venv/bin/activate
  - export $(cat .ci-secrets | xargs)

secrets:
  stage: secrets
  image: clevy/awssecrets
  before_script:
    - echo "Overriding common before_script to do nothing"
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_FOR_GITLAB_SECRETS_MANAGER
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_FOR_GITLAB_SECRETS_MANAGER
    - awssecrets --region us-east-1 --secret gitlab/driftdetector > .ci-secrets
  artifacts:
    # you want to set this to a value high enough to be used in all your stages,
    # but low enough that it gets invalidated quickly and needs to be regenerated later
    expire_in: 30 min 
    paths:
      # this will be available by default in all the next stages
      - .ci-secrets

test:
  stage: test
  script:
    - make test
  except:
    - develop
    - master

deploy-dev:
  stage: deploy-dev
  script:
    - make test
    - make deploy-dev
  only:
    - develop

deploy-prod:
  stage: deploy-prod
  script:
    - make test
    - make deploy-prod
    - make publish
  only:
    - master

