stages:
  - secrets
  - deploy

secrets:
  stage: secrets
  image: clevy/awssecrets
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_FOR_GITLAB_SECRETS_MANAGER
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_FOR_GITLAB_SECRETS_MANAGER
    - awssecrets --region us-east-1 --secret gitlab/fairbilet > .ci-secrets
  artifacts:
    # you want to set this to a value high enough to be used in all your stages,
    # but low enough that it gets invalidated quickly and needs to be regenerated later
    expire_in: 30 min 
    paths:
      # this will be available by default in all the next stages
      - .ci-secrets


master-deploy:
  stage: deploy
  image: $CI_REGISTRY/pattern-match/dockerfiles/hugoawscli
  before_script:
    - export $(cat .ci-secrets | xargs)
  script:
    - echo "Very very strange"

