AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS

  Sample SAM Template for AWS

  '
Parameters:
  SlackWebhook:
    Type: String
  Cron:
    Type: String
Globals:
  Function:
    Timeout: 300
Resources:
  DriftDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DriftDetector
      CodeUri: s3://pattern-match-drift-detector-dev-eu-west-1/d702cfb6076a56cd529dcc9bd0987804
      Handler: drift-detector.lambda_handler
      Runtime: python3.7
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Action:
          - cloudformation:Describe*
          - cloudformation:Detect*
          - cloudformation:List*
          Resource:
          - '*'
          Effect: Allow
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'
          Effect: Allow
      Environment:
        Variables:
          SLACK_WEBHOOK:
            Ref: SlackWebhook
      Events:
        RunOnSchedule:
          Type: Schedule
          Properties:
            Schedule:
              Fn::Sub: cron(${Cron})
