AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS CloudFormation drift-detector to Slack'
Parameters:
  SlackWebhook:
    Type: String
  Cron:
    Type: String
  ShowInSyncResources:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: 'Display resources that have no drift (in sync)'
    Type: String
  StackRegex:
    Type: String
Globals:
  Function:
    Timeout: 300
Metadata:
  AWS::ServerlessRepo::Application:
    Name: slack-drift-detector-notification
    Description: Serverless stack which notifies about drift detection of your stacks to your Slack
    Author: pattern-match-team
    SpdxLicenseId: Apache-2.0
    LicenseUrl: docs/LICENCE
    ReadmeUrl: docs/README.md
    Labels: ['cloudformation', 'slack', 'drift']
    HomePageUrl: https://driftdetector.com
    SemanticVersion: 2.0.0
    SourceCodeUrl: https://github.com/patternmatch/aws-drift-detector-slack

Resources:
  DriftDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: drift_detector.lambda_handler
      Runtime: python3.7
      Policies:
      - ReadOnlyAccess
      - Version: '2012-10-17'
        Statement:
        - Action:
          - cloudformation:Describe*
          - cloudformation:Detect*
          - cloudformation:List*
          Resource:
          - '*'
          Effect: Allow
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'
          Effect: Allow
      Environment:
        Variables:
          SLACK_WEBHOOK:
            Ref: SlackWebhook
          SHOW_IN_SYNC:
            Ref: ShowInSyncResources
          STACK_REGEX:
            Ref: StackRegex
      Events:
        RunOnSchedule:
          Type: Schedule
          Properties:
            Schedule:
              Fn::Sub: cron(${Cron})
