AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Parameters:
  SlackWebhook:
    Type: String

  Cron:
    Type: String

Globals:
  Function:
    Timeout: 300

Resources:
  DriftDetectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: drift-detector.lambda_handler
      Runtime: python3.7
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Action:
          - cloudformation:Describe*
          - cloudformation:Detect*
          - cloudformation:List*
          Resource:
          - "*"
          Effect: Allow
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: "*"
          Effect: Allow
      Environment:
        Variables:
          SLACK_WEBHOOK: !Ref SlackWebhook
      Events:
        RunOnSchedule:
          Type: Schedule
          Properties:
            Schedule: !Sub "cron(${Cron})"